repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["--config=./pyproject.toml"]
        exclude: ^tests/fixtures/
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: ["--config=./.flake8"]
        exclude: ^tests/fixtures/
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        exclude: ^tests/fixtures/
